USE PRACTICE;


SELECT  COUNT(MEM_NO)
  FROM  CUSTOMER
 WHERE  YEAR(JOIN_DATE) = 2019
   AND  MONTH(BIRTHDAY) BETWEEN 4 and 6;
   
SELECT  *
  FROM  SALES;
  
SELECT  *
  FROM  PRODUCT;

SELECT  AVG(A.SALES_QTY * B.PRICE)
		,SUM(A.SALES_QTY * B.PRICE) / COUNT(A.ORDER_NO)
  FROM  SALES AS A
  LEFT
  JOIN  PRODUCT AS B
    ON  A.PRODUCT_CODE = B.PRODUCT_CODE
 WHERE  A.MEM_NO <> 9999999;
 

SELECT  *
  FROM  (
		SELECT  MEM_NO
				,SUM(SALES_QTY) AS 구매수량
				,ROW_NUMBER() OVER (ORDER BY SUM(SALES_QTY) DESC) AS 순위방향
		  FROM  SALES
		 WHERE  MEM_NO <> 9999999
		 GROUP
			BY  MEM_NO
				) AS A
HAVING  순위방향 <= 10;   

CREATE VIEW SALES_GENDER_BRAND AS
SELECT  A.*
		,B.GENDER
        ,C.BRAND
  FROM  SALES AS A
  LEFT
  JOIN  CUSTOMER AS B
    ON  A.MEM_NO = B.MEM_NO
  LEFT
  JOIN  PRODUCT AS C
    ON  A.PRODUCT_CODE = C.PRODUCT_CODE;
  
SELECT  *
  FROM  SALES_GENDER_BRAND;
  
  
DELIMITER //
CREATE PROCEDURE CUSTOMER_BIRTHDAY(IN INPUT_A INT, INPUT_B INT)
BEGIN
	SELECT  *
	  FROM  CUSTOMER
	 WHERE  MONTH(BIRTHDAY) BETWEEN INPUT_A AND INPUT_B;
END //
DELIMITER ;

CALL CUSTOMER_BIRTHDAY(3,4);

CREATE TABLE SALES_MART AS
SELECT  A.*
		,B.CATEGORY
        ,B.TYPE
        ,A.SALES_QTY*B.PRICE AS 구매금액
  FROM  SALES AS A
  LEFT
  JOIN  PRODUCT AS B
    ON  A.PRODUCT_CODE = B.PRODUCT_CODE;
    
SELECT  *
  FROM  SALES_MART;

SELECT  CATEGORY
		,TYPE
        ,SUM(구매금액) AS 구매금액_합
  FROM  SALES_MART
 GROUP
    BY  CATEGORY
		,TYPE;
     
/* 재구매율 & 구매주기 분석*/

SELECT  *
  FROM  SALES;

/* 재구매여부, 구매간격, 구매주기 */

DROP TABLE PUR_CYCLE_TABLE;

CREATE TABLE PUR_CYCLE_TABLE AS
SELECT  *
		,CASE WHEN DATE_ADD(firstpurchase, INTERVAL +1 DAY) <= recentpurchase THEN 'Y'
			  ELSE 'N' END AS 재구매여부
		,DATEDIFF(recentpurchase, firstpurchase) AS 구매간격
        ,CASE WHEN purchasecount-1 = 0 OR DATEDIFF(recentpurchase, firstpurchase) = 0 THEN 0
			  ELSE DATEDIFF(recentpurchase, firstpurchase)/(purchasecount-1) END AS 구매주기
  FROM  (
		SELECT  MEM_NO
				,MIN(ORDER_DATE) AS firstpurchase
				,MAX(ORDER_DATE) AS recentpurchase
				,COUNT(ORDER_DATE) AS purchasecount
		  FROM  SALES
		 WHERE  MEM_NO <> '9999999'
		 GROUP
			BY  MEM_NO
		) AS A;

SELECT  *
  FROM  PUR_CYCLE_TABLE
 WHERE  MEM_NO='1000021'; 
 
SELECT  *
  FROM  SALES
 WHERE  MEM_NO='1000021'; 
 
SELECT  COUNT(DISTINCT MEM_NO) AS 구매회원수
		,COUNT(DISTINCT CASE WHEN 재구매여부 = 'Y' THEN MEM_NO END) AS 재구매회원수
  FROM  PUR_CYCLE_TABLE;

SELECT  COUNT(MEM_NO)
		,COUNT(DISTINCT MEM_NO)
  FROM  PUR_CYCLE_TABLE;
  
SELECT  AVG(구매주기)
  FROM  PUR_CYCLE_TABLE
 WHERE  구매주기 <> 0;



  
